CREATE TABLE Towns
(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Adresses
(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
AdressTest NVARCHAR(50) NOT NULL,
TownId INT NOT NULL
)

CREATE TABLE Departments
(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Employees
(
Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FirstName NVARCHAR(50) NOT NULL,
MiddleName NVARCHAR(50),
LastName NVARCHAR(50) NOT NULL,
JobTitle NVARCHAR(50) NOT NULL,
DepartmentId INT NOT NULL,
HireDate DATE NOT NULL,
AdressId INT NOT NULL
)